type Mutation {
  addOneDirectMessage(input: DirectMessageInput!): DirectMessage
  addManyDirectMessage(input: [DirectMessageInput!]!): [DirectMessage]
  updateOneDirectMessage(input: DirectMessageInput!): DirectMessage
  updateManyDirectMessage(input: [DirectMessageInput!]!): [DirectMessage]
  removeOneDirectMessage(id: ID!): DirectMessage
  removeManyDirectMessage(ids: [ID!]!): [DirectMessage]
  addOneDirectRoom(input: DirectRoomInput!): DirectRoom
  addManyDirectRoom(input: [DirectRoomInput!]!): [DirectRoom]
  updateOneDirectRoom(input: DirectRoomInput!): DirectRoom
  updateManyDirectRoom(input: [DirectRoomInput!]!): [DirectRoom]
  removeOneDirectRoom(id: ID!): DirectRoom
  removeManyDirectRoom(ids: [ID!]!): [DirectRoom]


  addOneMessage(input: MessageInput!): Message
  addManyMessage(input: [MessageInput!]!): [Message]
  updateOneMessage(input: MessageInput!): Message
  updateManyMessage(input: [MessageInput!]!): [Message]
  removeOneMessage(id: ID!): Message
  removeManyMessage(ids: [ID!]!): [Message]

  addOneRoom(input: RoomInput!): Room
  addManyRoom(input: [RoomInput!]!): [Room]
  updateOneRoom(input: RoomInput!): Room
  updateManyRoom(input: [RoomInput!]!): [Room]
  removeOneRoom(id: ID!): Room
  removeManyRoom(ids: [ID!]!): [Room]
  addOneUser(input: UserInput!): User
  addManyUser(input: [UserInput!]!): [User]
  updateOneUser(input: UserInput!): User
  updateManyUser(input: [UserInput!]!): [User]
  removeOneUser(id: ID!): User
  removeManyUser(ids: [ID!]!): [User]
}
