type User {
  id: ID
  username: String
  email: String
  # password: String
  # role: String
  directRooms: [DirectRoom]
  rooms: [Room]
}

input UserInput {
  id: ID
  username: String
  email: String
}
